import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — AI Setter",
  description: "Terms of service for the AI Setter Instagram messaging demo.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-sm leading-relaxed">
      <h1 className="mb-2 text-2xl font-semibold">Terms of Service</h1>
      <p className="mb-8 text-muted-foreground">Last updated: 2026-05-07</p>

      <section className="space-y-6">
        <p>
          AI Setter (the &quot;App&quot;) is a non-commercial portfolio demo of
          the Meta Graph API for Instagram messaging. By interacting with an
          Instagram account that has authorised the App, you agree to these
          terms.
        </p>

        <h2 className="text-lg font-semibold">Acceptable use</h2>
        <p>
          Do not use the App to harass, defraud, send unsolicited bulk messages,
          violate Meta&apos;s Platform Terms, or attempt to disrupt the service.
          Automated abuse is prohibited.
        </p>

        <h2 className="text-lg font-semibold">No warranty</h2>
        <p>
          The App is provided as-is, without warranty of any kind. Replies are
          generated by a large language model and may be inaccurate, irrelevant,
          or unsuitable for any particular purpose.
        </p>

        <h2 className="text-lg font-semibold">Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, the operator of the App is
          not liable for any direct, indirect, incidental, or consequential
          damages arising from use of the App.
        </p>

        <h2 className="text-lg font-semibold">Termination</h2>
        <p>
          The operator may discontinue the App at any time. You may stop
          interacting with the connected Instagram account at any time and may
          send <code>STOP</code> in a Direct Message to opt out of further
          automated replies.
        </p>

        <h2 className="text-lg font-semibold">Governing law</h2>
        <p>
          These terms are governed by the laws of Germany, without regard to
          conflict of laws principles.
        </p>

        <h2 className="text-lg font-semibold">Contact</h2>
        <p>christianjheggfer@gmail.com</p>
      </section>
    </main>
  );
}
